import type { ConversationMessage } from '../types';
import { KnowledgeGraph } from '../graph/KnowledgeGraph';
import { ObsidianFormatter, type ObsidianExportOptions } from './ObsidianFormatter';
import { CornellFormatter } from './CornellFormatter';

export class MarkdownExporter {
  private obsidianFormatter = new ObsidianFormatter();
  private cornellFormatter = new CornellFormatter();

  /** Export full document: Obsidian markdown + Cornell notes */
  export(
    messages: ConversationMessage[],
    graph: KnowledgeGraph,
    options: Partial<ObsidianExportOptions> = {}
  ): string {
    const rootNode = graph
      .getNodes()
      .find((n) => n.id === graph.getRootId());
    const title =
      options.title ??
      `Conversation: ${rootNode?.label ?? 'Untitled'}`;

    const tags = options.tags ?? this.extractTags(graph);

    const fullOptions: ObsidianExportOptions = {
      title,
      source: options.source ?? this.detectSource(),
      date:
        options.date ??
        new Date().toISOString().split('T')[0],
      tags,
    };

    const parts: string[] = [];

    // Part 1: Obsidian-formatted knowledge structure
    parts.push(
      this.obsidianFormatter.format(graph, fullOptions)
    );

    // Separator
    parts.push('');
    parts.push('---');
    parts.push('');

    // Part 2: Cornell notes
    parts.push(
      this.cornellFormatter.format(messages, graph)
    );

    // Footer
    parts.push('---');
    parts.push(
      `*Generated by MindFlow on ${fullOptions.date} from ${fullOptions.source} conversation*`
    );

    return parts.join('\n');
  }

  /** Export mind map only as markdown (for quick copy) */
  exportMindMapOnly(graph: KnowledgeGraph): string {
    return graph.toMarkdownTree();
  }

  private extractTags(graph: KnowledgeGraph): string[] {
    return graph
      .getTopNodes(5)
      .map((n) =>
        n.label
          .toLowerCase()
          .replace(/\s+/g, '-')
          .replace(/[^\w\u4e00-\u9fff-]/g, '')
      )
      .filter((t) => t.length > 0);
  }

  private detectSource(): string {
    if (typeof window !== 'undefined') {
      const url = window.location.hostname;
      if (url.includes('chatgpt') || url.includes('openai'))
        return 'chatgpt.com';
      if (url.includes('claude')) return 'claude.ai';
      if (url.includes('gemini')) return 'gemini.google.com';
      return url;
    }
    return 'unknown';
  }
}

/** Trigger browser download of the markdown file */
export function downloadMarkdown(
  content: string,
  filename: string
): void {
  const blob = new Blob([content], {
    type: 'text/markdown;charset=utf-8',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
